config/routes.rb
Rails.application.routes.draw do
  resources :bugs
  resources :users

end

app/models/bug.rb
class Bug < ActiveRecord::Base
  belongs_to :owner, class_name: 'User'

  enum status: [:open, :assign, :resolve,:close]

  def next_possible_status
     case status.to_sym
        when :open
          %w(open assign resolve)
        when :assign
          %w(assign resolve)
        when :resolve
          %w(resolve close)
        when :close
          %w(close open)
        else
          %w(open assign resolve close)
     end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bugs, foreign_key: :owner_id

  def full_name
    [first_name, last_name].join(' ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_bug, only: [:show, :edit, :update, :destroy]

  # GET /bugs
  # GET /bugs.json
  def index
    @bugs = Bug.all
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show
  end

  # GET /bugs/new
  def new
    @bug = Bug.new(status: :open)
    @users = User.all
  end

  # GET /bugs/1/edit
  def edit
  end

  # POST /bugs
  # POST /bugs.json
  def create
    @bug = Bug.new(bug_params)

    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render :show, status: :created, location: @bug }
      else
        format.html { render :new }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bugs/1
  # PATCH/PUT /bugs/1.json
  def update
    respond_to do |format|
      if @bug.update(bug_params)
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug }
      else
        format.html { render :edit }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  def destroy
    @bug.destroy
    respond_to do |format|
      format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug
      @bug = Bug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bug_params
      params.require(:bug).permit(:title, :detail, :owner_id, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bugs/_form.html.slim
= form_for @bug, html: { class: "form form-horizontal bug" } do |f|
  .form-group
    = f.label :title, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :title, :class => 'form-control'
    = f.error_span(:title)
  .form-group
    = f.label :detail, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :detail, :class => 'form-control'
    = f.error_span(:detail)
  .form-group
    = f.label :owner_id, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.select :owner_id, options_from_collection_for_select(User.all, :id, :full_name), include_blank: true, :class => 'form-control'
    = f.error_span(:owner_id)
    = f.error_span(:detail)
  .form-group
    = f.label :status, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.select :status, @bug.next_possible_status, class: 'form-control'


  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), bugs_path, :class => 'btn'

app/views/bugs/edit.html.slim
- model_class = Bug
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/bugs/index.html.slim
- model_class = Bug
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:title)
      th= model_class.human_attribute_name(:detail)
      th= model_class.human_attribute_name(:owner)
      th= model_class.human_attribute_name(:status)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @bugs.each do |bug|
      tr
        td= link_to bug.id, bug_path(bug)
        td= bug.title
        td= bug.detail
        td= bug.owner.full_name
        td= bug.status
        td=l bug.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_bug_path(bug), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), bug_path(bug), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_bug_path, :class => 'btn btn-primary'

app/views/bugs/new.html.slim
- model_class = Bug
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/bugs/show.html.slim
- model_class = Bug
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:title) + ': '
  = @bug.title
p
  strong= model_class.human_attribute_name(:detail) + ': '
  = @bug.detail
p
  strong= model_class.human_attribute_name(:owner_id) + ': '
  = @bug.owner.full_name
p
  strong= model_class.human_attribute_name(:status) + ': '
  = @bug.status

= link_to t('.back', :default => t("helpers.links.back")), bugs_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_bug_path(@bug), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), bug_path(@bug), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Bugzilla"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="#"Bugzilla
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li= link_to 'Bugs', bugs_path

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar

    footer

app/views/users/_form.html.slim
= form_for @user, html: { class: "form form-horizontal user" } do |f|
  .form-group
    = f.label :first_name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :first_name, :class => 'form-control'
    = f.error_span(:first_name)
  .form-group
    = f.label :last_name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :last_name, :class => 'form-control'
    = f.error_span(:last_name)
  .form-group
    = f.label :email, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :email, :class => 'form-control'
    = f.error_span(:email)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      '
      = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/edit.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/index.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:first_name)
      th= model_class.human_attribute_name(:last_name)
      th= model_class.human_attribute_name(:email)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @users.each do |user|
      tr
        td= link_to user.id, user_path(user)
        td= user.first_name
        td= user.last_name
        td= user.email
        td=l user.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/show.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:first_name) + ':'
  br
  = @user.first_name
p
  strong= model_class.human_attribute_name(:last_name) + ':'
  br
  = @user.last_name
p
  strong= model_class.human_attribute_name(:email) + ':'
  br
  = @user.email

= link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'